name: macros_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-167.0.dev

# Add regular dependencies here.
dependencies:
  json: ^0.20.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  build_runner: ^2.4.10
  lints: ^4.0.0
  test: ^1.24.0
  macros: ^0.1.0-main.5
